name: Fjordesign
favicon: null
layout_spectrum: 0.406238900963217
typography_spectrum: 0.22228096146136522
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#202020'
    - '#66696e'
    - '#46474d'
    - '#fffdfa'
    - '#dcd5d8'
  brandStrength: 0.4375
  lightness: 0.037656724685803056
  saturation: 0.06487362994812429
  rhythmicContrast: 0.2906958188395947
purpose: []
