name: Fjordesign
favicon: null
layout_spectrum: 0.406238900963217
typography_spectrum: 0.30374
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231e1c'
    - '#4b4543'
    - '#8a8482'
    - '#fefefe'
    - '#c3bdbf'
  brandStrength: 0.4375
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
